# Generated by Django 2.1.7 on 2019-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='the end is near', max_length=50),
            preserve_default=False,
        ),
    ]
